language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.3
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone 7
env: NODE_VERSION=10.11.0

branches:
  only:
  - master

cache: yarn

install:
- nvm --version
- echo $NODE_VERSION
- sudo launchctl limit maxfiles 2048 unlimited
- sudo ulimit -n 10000
- brew tap wix/brew
- brew install applesimutils
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- echo `node --version`
- nvm alias default $NODE_VERSION
- npm i -g yarn
- npm install -g react-native-cli
- npm install -g detox-cli
- cd Example
- yarn
- export PRODUCT_BUNDLE_IDENTIFIER="com.swmansion.rn_gesture_handler_example"
- detox build --configuration ios.sim.debug > /dev/null

script:
- detox test -d --no-color --configuration ios.sim.debug --cleanup
